<a href="https://colab.research.google.com/github/AkkiNikumbh/DL-EXPERIMENTS/blob/main/AkashSingh_23CS036_Exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### WHY TENSORS & NUMPY ?

In [ ]:
import torch
import numpy as np
import time

# WHY TENSORS & NUMPY -

# Create 1 million elements
size = 1_000_000
list_a = list(range(size))
list_b = list(range(size))

# 1. Standard Python List (Using a loop)
start = time.time()
list_res = [list_a[i] + list_b[i] for i in range(size)]
print(f"Python List time:  {(time.time() - start):.5f} seconds")

# 2. NumPy (Vectorized)
np_a = np.arange(size)
np_b = np.arange(size)
start = time.time()
np_res = np_a + np_b
print(f"NumPy time:        {(time.time() - start):.5f} seconds")

# 3. PyTorch (Vectorized on CPU)
pt_a = torch.arange(size)
pt_b = torch.arange(size)
start = time.time()
pt_res = pt_a + pt_b
print(f"PyTorch (CPU) time: {(time.time() - start):.5f} seconds")

Python List time:  0.12768 seconds
NumPy time:        0.00276 seconds
PyTorch (CPU) time: 0.00581 seconds


### CREATING 1D, 2D & 3D TENSORS

In [ ]:
import torch
import numpy as np

# PyTorch
pt_3d = torch.rand(2, 3, 4) # (Depth, Rows, Cols)
# NumPy
np_3d = np.random.rand(2, 3, 4)

### ELEMENT WISE OPERATIONS

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(a + b)       # Addition: [5, 7, 9]
print(a * b)       # Multiplication: [4, 10, 18]
print(torch.exp(a)) # Exponential of every element

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor([ 2.7183,  7.3891, 20.0855])


### INDEXING AND SLICING OPERATIONS

In [ ]:
data = torch.tensor([[10, 20, 30], [40, 50, 60]])

# Extracting a sub-tensor (First row, first two columns)
print(data[0, 0:2]) # Result: [10, 20]

# Boolean Masking (Find all values > 25)
mask = data > 25
print(data[mask])   # Result: [30, 40, 50, 60]

tensor([10, 20])
tensor([30, 40, 50, 60])


### RESHAPING & DIMENSION MANIPULATION

In [ ]:
x = torch.arange(6) # [0, 1, 2, 3, 4, 5]

# PyTorch Reshaping
viewed = x.view(2, 3)
expanded = x.unsqueeze(0) # Becomes shape (1, 6)

# NumPy Reshaping
x_np = np.arange(6)
reshaped_np = x_np.reshape(2, 3)

### BROADCASTING

In [ ]:
# Shape (3, 1)
m1 = torch.tensor([[1], [2], [3]])
# Shape (3,) -> treated as (1, 3)
m2 = torch.tensor([10, 20, 30])

# Result is Shape (3, 3)
# The row [1] is added to [10, 20, 30]
# The row [2] is added to [10, 20, 30]...
print(m1 + m2)

tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])


### INPLACE VS OUTPLACE

In [ ]:
x = torch.tensor([1.0, 2.0])

# Out-of-place: x doesn't change, y is a new tensor
y = x.add(5)
print(x) # [1, 2]

# In-place: x ITSELF is modified
x.add_(5)
print(x) # [6, 7]